### ISSUE TITLE
broccoli-sass conflict

### ISSUE THREAD

**Issue by miguelcobain** [pixelhandler/ember-off-canvas-components#4]
Like @altrim stated at https://github.com/miguelcobain/ember-paper/issues/12, we can't use this method of using sass in an addon with another project that already uses sass.

Steps to reproduce the problem:

```bash
ember new eoc-test
npm install --save-dev pixelhandler/ember-off-canvas-components
ember server #runs ok!
npm install --save-dev broccoli-sass
ember server #this fails
```

The output:
```
$ ember server
version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
Object.keys called on non-object
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at StylePlugin.toTree (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/preprocessors/style-plugin.js:24:22)
    at /home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/preprocessors.js:104:26
    at Array.forEach (native)
    at processPlugins (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/preprocessors.js:103:11)
    at module.exports.preprocessCss (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/preprocessors.js:75:10)
    at Class.Addon.compileStyles (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/models/addon.js:193:27)
    at Class.Addon.treeForAddon (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/models/addon.js:174:25)
    at Class._treeFor (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/models/addon.js:118:31)
    at Class.treeFor (/home/jcandrade/Documents/workspace/tmp/eoc-test/node_modules/ember-cli/lib/models/addon.js:97:19)
```

**Comment by stefanpenner** [comment]
this is fixed on master

**Comment by pixelhandler** [comment]
@stefanpenner thanks :) I'll give it another go with sass
